Traceback (most recent call last):
  File "C:\Users\aaron\CODING\SCAI\train.py", line 24, in <module>
    x = tf.keras.layers.Dropout(wandb.config.dropout)(x)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\regularization\dropout.py", line 80, in __init__
    raise ValueError(f'Invalid value {rate} received for '
ValueError: Invalid value 1.2856762838374884 received for `rate`, expected a value between 0 and 1.