2023-01-04 20:11:01,305 INFO    MainThread:21064 [wandb_setup.py:_flush():68] Configure stats pid to 21064
2023-01-04 20:11:01,306 INFO    MainThread:21064 [wandb_setup.py:_flush():68] Loading settings from C:\Users\aaron\.config\wandb\settings
2023-01-04 20:11:01,306 INFO    MainThread:21064 [wandb_setup.py:_flush():68] Loading settings from C:\Users\aaron\CODING\SCAI\wandb\settings
2023-01-04 20:11:01,306 INFO    MainThread:21064 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-04 20:11:01,306 INFO    MainThread:21064 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'dmg_NN.py', 'program': 'c:\\Users\\aaron\\CODING\\SCAI\\dmg_NN.py'}
2023-01-04 20:11:01,308 INFO    MainThread:21064 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\aaron\CODING\SCAI\wandb\run-20230104_201101-gs6135gj\logs\debug.log
2023-01-04 20:11:01,309 INFO    MainThread:21064 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\aaron\CODING\SCAI\wandb\run-20230104_201101-gs6135gj\logs\debug-internal.log
2023-01-04 20:11:01,309 INFO    MainThread:21064 [wandb_init.py:init():516] calling init triggers
2023-01-04 20:11:01,309 INFO    MainThread:21064 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-04 20:11:01,309 INFO    MainThread:21064 [wandb_init.py:init():569] starting backend
2023-01-04 20:11:01,309 INFO    MainThread:21064 [wandb_init.py:init():573] setting up manager
2023-01-04 20:11:01,326 INFO    MainThread:21064 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2023-01-04 20:11:01,345 INFO    MainThread:21064 [wandb_init.py:init():580] backend started and connected
2023-01-04 20:11:01,359 INFO    MainThread:21064 [wandb_init.py:init():658] updated telemetry
2023-01-04 20:11:01,439 INFO    MainThread:21064 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-01-04 20:11:04,584 WARNING MsgRouterThr:21064 [router.py:message_loop():77] message_loop has been closed
2023-01-04 20:11:06,510 ERROR   MainThread:21064 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
